<a href="https://colab.research.google.com/github/jeraldflowers/Linear-Algebra-for-ML-and-PCA/blob/main/decompose_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([[3,2], [4,1]])
print(A)

[[3 2]
 [4 1]]


In [ ]:
from enum import auto
autovalores, autovectores = np.linalg.eig(A)

print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [ ]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))

In [ ]:
print(A_calc)

[[3. 2.]
 [4. 1.]]


In [ ]:
A = np.array([[3,2], [2,3]])
print(A)

[[3 2]
 [2 3]]


In [ ]:
print(A == A.T)

[[ True  True]
 [ True  True]]


In [ ]:
autovalores, autovectores = np.linalg.eig(A)
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [ ]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
print(A_calc)

[[3. 2.]
 [2. 3.]]
