<a href="https://colab.research.google.com/github/jeraldflowers/Linear-Algebra-for-ML-and-PCA/blob/main/decomposition_of_a_non_square_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1,2,3], [3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [ ]:
U, D, V = np.linalg.svd(A)

In [ ]:
print(U)

[[-0.46410668 -0.88577931]
 [-0.88577931  0.46410668]]


In [ ]:
print(D)

[7.97638869 0.61418515]


In [ ]:
print(np.diag(D))

[[7.97638869 0.        ]
 [0.         0.61418515]]


In [ ]:
print(V)

[[-0.39133557 -0.5605708  -0.72980603]
 [ 0.8247362   0.13817999 -0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]
